# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 21:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20160528_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 28, 21, 58, 55, 790965, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
